- src/pvrclient-nextpvr.cpp
- src/pvrclient-nextpvr.h
This request fix the not needed gcc compiler warning about wrong value types.
> Fix compiler warnings

- pvr.nextpvr/addon.xml
- pvr.nextpvr/changelog.txt
- src/pvrclient-nextpvr.cpp
If nobody objects this is going in later today.
> Sync with API 1.9.6

- pvr.nextpvr/addon.xml
- pvr.nextpvr/changelog.txt
- src/RingBuffer.cpp
- src/RingBuffer.h
- src/Socket.cpp
- src/liveshift.cpp
- src/pvrclient-nextpvr.cpp
- src/pvrclient-nextpvr.h
- fixed issue where RPi user were unable to watch live tv due to subtle socket differences on that platform
- fixed issue where recording list would get out of date and not reflect reality of backend
> Added fixes already included in the Helix branch

- pvr.nextpvr/addon.xml
- pvr.nextpvr/changelog.txt
- src/client.cpp
Add-on part of https://github.com/xbmc/xbmc/pull/7536
> Minimal support for PVR API 2.1.0

- pvr.nextpvr/resources/language/resource.language.en_gb/strings.po
As requested in pull request #17 - this pull request is the same as that one, only on the Isengard branch. First commit was to update my copy to match current kodi-pvr copy, second one to implement the changes.
> Update string #30133 to "Post-Padding (minutes)" (Isengard branch)

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
Add-on part of https://github.com/xbmc/xbmc/pull/7570
> Automatically fill in platform and library name

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
Addon part of xbmc/xbmc#7626
Add on currently using 1.9.7 API compatibility code
No further changes required for minimal support
> Bump add-on for PVR API 3.0.0 (Compatibility mode)

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- pvr.nextpvr/resources/language/resource.language.en_us/strings.po
- pvr.nextpvr/resources/settings.xml
- src/client.cpp
- src/client.h
- src/pvrclient-nextpvr.cpp
Added support for dynamic downloading of artwork in TV guide
Added support for keyword timers
Fixed an issue with updating timers
> Improved support for Jarvis timers and TV Guide artwork

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/pvrclient-nextpvr.cpp
This patch fixes an issue one user saw relating to recording groups. 
Upped minimum NextPVR version to 3.6.0
> Fixed bug that could occur with recording groups

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
Addon side of https://github.com/xbmc/xbmc/pull/8494
> Updated to GUI API v5.10.0

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- pvr.nextpvr/resources/language/resource.language.en_gb/strings.po
- src/README
- src/pvrclient-nextpvr.cpp
- fixed issue with Transifex overwriting strings with older strings
- added extra 'Repeating (keyword)' string to correct duplicate recording type entry
> Fixed two errors with message strings

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/client.cpp
Updated to PVR Addon API 4.2.0
> Updated to PVR Addon API 4.2.0 

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/client.cpp
- src/client.h
- src/pvrclient-nextpvr.cpp
- src/pvrclient-nextpvr.h
For details refer to https://github.com/xbmc/xbmc/pull/8736
Before this PR can go in, https://github.com/xbmc/xbmc/pull/8736 must be merged.
> Implement PVR API 5.0.0

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/pvrclient-nextpvr.cpp
-Fixed issue where user couldn't select to only record new episodes
-Fixed issue with updating one-off recordings
-Fixed issue where pre/post padding was not being loaded with recording list
> Fixed issues editing recordings, and selecting to record only new episodes

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/pvrclient-nextpvr.cpp
Refer to https://github.com/xbmc/xbmc/pull/9290 and https://github.com/xbmc/xbmc/pull/9295 for details.
> PVR API 5.1.0

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/Socket.cpp
- src/client.cpp
- src/client.h
- src/liveshift.h
- src/pvrclient-nextpvr.h
https://github.com/xbmc/xbmc/pull/9804 and https://github.com/xbmc/xbmc/pull/9671 for reference
> Fix includes

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/pvrclient-nextpvr.cpp
- src/pvrclient-nextpvr.h
Fixed issue where the recording/timers lists were no longer automatically updating
> Fixed recording/timers refresh issue

- CMakeLists.txt
- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
Related to kodi Pull Request xbmc/xbmc#12029
Not merge in before is in Kodi!
> change to automatic depends set on addon.xml

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/client.cpp
related to Kodi pull request xbmc/xbmc#12109
> remove no more needed version functions

- debian/control
- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
This is related to xbmc/xbmc#12114 and xbmc/xbmc#12116
> Update addon Version related to Kodi changes

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/client.cpp
Related kodi PR: https://github.com/xbmc/xbmc/pull/12303
> Added minimalistic support for PVR Addon API 5.3.0

- debian/kodi-pvr-nextpvr.install
This also affects Krypton. After view, please merge into the Krypton branch as well.
> fix install path

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/client.cpp
Add stub GetEPGTagEdl function added in PVR api: https://github.com/xbmc/xbmc/pull/13720
> PVR API 5.9.0

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/client.cpp
> PVR API 5.10.0

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- src/buffers/Buffer.h
- src/buffers/RecordingBuffer.cpp
- src/buffers/TimeshiftBuffer.cpp
- src/buffers/TimeshiftBuffer.h
- src/client.cpp
- src/pvrclient-nextpvr.cpp
- src/pvrclient-nextpvr.h
also, fix some cases were -1 should be returned instead of 0, when a failure occurs, when counting/listing recordings, and timers.
> Add implementation for GetReadStreamChunkSize()

- pvr.nextpvr/addon.xml.in
- pvr.nextpvr/changelog.txt
- pvr.nextpvr/resources/language/resource.language.en_gb/strings.po
- pvr.nextpvr/resources/settings.xml
- src/buffers/RollingFile.cpp
- src/client.cpp
- src/client.h
- src/pvrclient-nextpvr.cpp
Fixes and Recording alternative
> V3.3.14 Maintenance release

- pvr.nextpvr/changelog.txt
- src/Socket.cpp
- src/buffers/Buffer.h
- src/buffers/DummyBuffer.h
- src/buffers/RecordingBuffer.h
- src/client.cpp
- src/pvrclient-nextpvr.cpp
- src/pvrclient-nextpvr.h
Remove trailing spaces and tabs.
> Style Cleanup
